Repository ahmadsoe/ember-highcharts, pull requests merged in 2024-04, with the labels that each got.

#388 remove unnecessary dependency on holy-futuristic-template-namespacing…
  package.json
  yarn.lock
Labels: dependencies

#438 Bump deepmerge, remove vendor shim
  package.json
  vendor/shims/deepmerge.js
  yarn.lock
Labels: Internal

#442 Remove validate-peer-dependencies
  index.js
  package.json
Labels: Enhancement

#443 Update release-it setup
  package.json
  yarn.lock
Labels: Internal

#444 Drop support for Ember < 4.12
  .ember-cli
  .eslintignore
  .github/workflows/ci.yml
  .gitignore
  .npmignore
  .prettierignore
  .watchmanconfig
  CONTRIBUTING.md
  README.md
  blueprints/chart-test/files/tests/units/__path__/__test__.js
  index.js
  package.json
  tests/dummy/app/components/chart-highstock-interactive.js
  tests/dummy/app/components/chart-line-interactive.js
  tests/dummy/app/components/chart-scatter.js
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/helpers/index.js
  tests/integration/components/high-charts-test.js
  tests/unit/utils/chart-data-test.js
  yarn.lock
Labels: Breaking
