Repository ahmadsoe/ember-highcharts, pull requests merged in 2024-10, with the labels that each got.

#476 v2 test app path in README
  README.md
Labels: documentation

#472 Support treegraph and treemap modules
  ember-highcharts/src/components/high-charts.ts
  test-app/app/components/chart-treegraph.hbs
  test-app/app/components/chart-treegraph.js
  test-app/app/templates/index.hbs
Labels: enhancement

#487 docs: Remove global config reference
  README.md
Labels: documentation

#488 Fix test app component class names
  test-app/app/components/chart-heat-map.js
  test-app/app/components/chart-highstock-interactive.js
  test-app/app/components/chart-line-interactive.js
  test-app/app/components/chart-solid-gauge.js
Labels: internal

#484 docs: Remove reference to blueprints
  README.md
Labels: documentation

#489 Setup release-plan
  .github/workflows/ci.yml
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  .tool-versions
  CHANGELOG.md
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal
